site_name: RL ProtoKit Docs - Punk Edition
theme:
  name: material
  custom_dir: custom_theme
nav:
  - Home: index.html
plugins:
  - search
extra_css:
  - styles.css
extra_javascript:
  - script.js
markdown_extensions:
  - pymdownx.superfences
